### ISSUE TITLE
crash on android

### ISSUE THREAD

**Issue by ramsestom** [DanielUranga/extension-gpgrest#4]
On android, crash with the error message:

I/trace   ( 4388): WebView.hx:72: INIT Exception: JNI Exception
I/trace   ( 4388): Lib.hx:360: Null Function Pointer
I/trace   ( 4388): Called from extension.webview.WebView.open (extension/webview/WebView.hx line 34)
I/trace   ( 4388): Called from com.sempaigames.gplayrest.Auth.getAuthCode (com/sempaigames/gplayrest/Auth.hx line 86)
I/trace   ( 4388): Called from com.sempaigames.gplayrest.Auth.loginUsingAuthCode (com/sempaigames/gplayrest/Auth.hx line 214)
I/trace   ( 4388): Called from com.sempaigames.gplayrest.Auth.login (com/sempaigames/gplayrest/Auth.hx line 252)
I/trace   ( 4388): Called from com.sempaigames.gplayrest.GooglePlayGames.displayScoreboard (com/sempaigames/gplayrest/GooglePlayGames.hx line 57)
I/trace   ( 4388): Called from extension.multigames.Multigames.displayLeaderboard (extension/multigames/Multigames.hx
line 98)
I/trace   ( 4388): Called from ui.MainMenuState.click_leaderboard (ui/MainMenuState.hx line 146)
I/trace   ( 4388): Called from openfl._legacy.events.EventDispatcher.dispatchEvent (openfl/_legacy/events/EventDispatcher.hx line 98)
I/trace   ( 4388): Called from openfl._legacy.display.DisplayObject.__dispatchEvent (openfl/_legacy/display/DisplayObject.hx line 182)

I checked parametters received by the WebView.open() function called from Auth.getAuthCode() and the urlWhitelist is NULL. Don't know if that might be the cause of the problem or if this is actually a JNI binding issue in the webview extension (wich I succeded to make work once on android and there doesn't seem to be any update since so I don't think the problem is on the webview extension)

**Comment by fbricker** [comment]
Hi... You should not use this extension on android (for android use extension-googleplaygames instead).

**Comment by ramsestom** [comment]
Well I want to use this extension on android because I am planning to have my own leaderboard UI (by modifying leaderboard.hx) and to have this leaderboard ui shared by every platform my game would run on (android, ios, blackberry, windows phone).
I think the easiest way for this is to use gpgrest on each platform and just change the leaderboard UI of the extension-gpgrest lib to my own taste...

**Comment by DanielUranga** [comment]
It seems like extension-webiew is failing to initialize. In the logs can be read `I/trace ( 4388): WebView.hx:72: INIT Exception: JNI Exception` which comes from https://github.com/openfl/extension-webview/blob/master/extension/webview/WebView.hx#L95

**Comment by DanielUranga** [comment]
Pushed some commits to webview and native-dialogs extensions, should improve things.
